# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "AsyncFileResponse": "01_http.ipynb",
         "get_config": "01_scripts.ipynb",
         "patch_config": "01_scripts.ipynb",
         "patch_lib_name": "01_scripts.ipynb",
         "nbdev_build_docs_patched": "01_scripts.ipynb"}

modules = ["core.py",
           "http.py",
           "scripts.py"]

doc_url = "https://ephes.github.io/django_fileresponse/"

git_url = "https://github.com/ephes/django_fileresponse/tree/main/"

def custom_doc_links(name): return None
