# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"AsyncFileASGIHandler": "01_handlers.ipynb",
         "get_config": "01_scripts.ipynb",
         "patch_config": "01_scripts.ipynb",
         "patch_lib_name": "01_scripts.ipynb",
         "nbdev_build_docs_patched": "01_scripts.ipynb",
         "get_asgi_application": "02_asgi.ipynb",
         "AsyncResponse": "02_http.ipynb",
         "AiofileFileResponse": "02_http.ipynb",
         "AiobotocoreFileResponse": "02_http.ipynb"}

modules = ["handlers.py",
           "scripts.py",
           "asgi.py",
           "http.py"]

doc_url = "https://ephes.github.io/django_fileresponse/"

git_url = "https://github.com/ephes/django_fileresponse/tree/main/"

def custom_doc_links(name): return None
