# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_asgi.ipynb (unless otherwise specified).

__all__ = ['get_asgi_application']

# Cell

import django

from fileresponse.handlers import AsyncFileASGIHandler


def get_asgi_application():
    """
    Similar to django.core.asgi.get_asgi_application, but uses AsyncFileASGIHandler
    instead of Djangos ASGIHandler.
    """
    django.setup(set_prefix=False)
    return AsyncFileASGIHandler()