# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_asgi.ipynb (unless otherwise specified).

__all__ = ['get_asgi_application']

# Cell

import django

from fileresponse.handlers import AsyncFileASGIHandler


def get_asgi_application():
    django.setup(set_prefix=False)
    return AsyncFileASGIHandler()