# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_handlers.ipynb (unless otherwise specified).

__all__ = ['AsyncFileASGIHandler']

# Cell

from asgiref.sync import sync_to_async
from django.core.handlers.asgi import ASGIHandler


class AsyncFileASGIHandler(ASGIHandler):
    async def send_response(self, response, send):
        is_async_fileresponse = getattr(response, "is_async_fileresponse", False)
        if is_async_fileresponse:
            return await response.stream(send)
        else:
            return await super().send_response(response, send)