# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_http.ipynb (unless otherwise specified).

__all__ = ['AiofileFileResponse']

# Cell

import time
import aiofiles


class AiofileFileResponse:
    headers = {
        "Content-Type": "application/octet-stream"
    }
    streaming = True
    _resource_closers = []
    is_async_fileresponse = True

    def __init__(self, path, chunk_size=4096):
        self.path = path
        self.chunk_size = chunk_size
        self.status_code = 200
        self.raw_headers = {}

    def get(self, header, alternate=None):
        return None

    async def stream(self, send):
        started_serving = time.perf_counter()
        await send(
            {
                "type": "http.response.start",
                "status": self.status_code,
                "headers": self.raw_headers,
            }
        )
        async with aiofiles.open(self.path, mode="rb") as file:  # type: ignore
            more_body = True
            while more_body:
                chunk = await file.read(self.chunk_size)
                more_body = len(chunk) == self.chunk_size
                await send(
                    {
                        "type": "http.response.body",
                        "body": chunk,
                        "more_body": more_body,
                    }
                )
        self.elapsed = time.perf_counter() - started_serving