# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_scripts.ipynb (unless otherwise specified).

__all__ = ['nbdev_build_docs_patched']

# Cell

import re
import sys

from nbdev.export2html import nbdev_build_docs


def nbdev_build_docs_patched():
    print("hello world")
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(nbdev_build_docs())